# Website settings
url: "https://apc-llc.github.io"

# Internal nav
nav:
  main:
    blog: "/blog"
    talks: "/talks"
    projects: "/projects"
  blog:
    all: "/blog"
    popular: "/blog/popular"
    tags: "/blog/tags"
    rss: "/feed.xml"

# Bio settings
name: "Dmitry Mikushin"
description: "The home page of Dmitry Mikushin, GPU&amp;HPC engineer, co-founder of Purple Gaze Inc."
thumbnail_path: "profile-photos/apc_logo.png"
purplegaze_url: "https://purplegaze.io/"
apcllc_url: "https://parallel-computing.pro/"
unil_url: "https://www.unil.ch/hec-phd/en/home/menuinst/programs/phd-in-business-analytics/current-students.html"
website_repo_url: "https://github.com/apc-llc/apc-llc.github.io"
my_github_url: "https://github.com/dmikushin"
apcllc_github_url: "https://github.com/apc-llc"

# URLs
contact_urls:
  linkedin:
    url: "https://www.linkedin.com/company/applied-parallel-computing/about/?viewAsMember=true"
    label: "LinkedIn"
    icon: "linkedin-square"
  github:
    url: "https://github.com/apc-llc/"
    label: "GitHub"
    icon: "github-square"
  email:
    url: "mailto:contact@parallel-computing.pro"
    label: "Email"
    value: "contact@parallel-computing.pro"
    icon: "envelope-square"

# Jekyll build settings
paginate: 10
paginate_path: "/blog/page:num"
permalink: "/blog/:year/:month/:day/:title/"
sass:
  sass_dir: "/assets/css"
  style: :compressed
highlighter: rouge
timezone: 'Europe/Geneva'
repository: apc-llc/apc-llc.github.io

# Plugins (GitHub Pages only support a few)
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
